export const routes = {
  public: {
    home: "/",
    howItWorks: "/como-funciona",
    journey: "/sua-jornada",
    journeyResult: "/sua-jornada/resultado",
    therapists: "/terapeutas",
    therapistProfile: (slug: string) => `/terapeutas/${slug}`,
    reservation: "/reserva",
    reservationSuccess: "/reserva/sucesso",
    therapies: "/terapias",
    therapyDetail: (slug: string) => `/terapias/${slug}`,
    forTherapists: "/para-terapeutas",
    therapistPlans: "/para-terapeutas/planos",
    clientSignIn: "/cliente/login",
    clientSignUp: "/cliente/cadastro",
    therapistSignIn: "/terapeuta/login",
    therapistSignUp: "/terapeuta/cadastro",
    confirmEmail: "/confirmar-email",
    therapistCheckout: "/terapeuta/checkout",
    signIn: "/entrar",
    signUp: "/cadastro",
    resetPassword: "/reset-senha",
    help: "/ajuda",
    terms: "/termos",
    privacy: "/privacidade",
  },
  patient: {
    home: "/app",
    overview: "/app",
    encounters: "/app/encontros",
    encounterDetail: (bookingId: string) => `/app/encontros/${bookingId}`,
    sessions: "/app/sessoes",
    upcomingSessions: "/app/sessoes/proximas",
    sessionHistory: "/app/sessoes/historico",
    sessionDetail: (slug: string) => `/app/sessoes/${slug}`,
    messages: "/app/mensagens",
    favorites: "/app/favoritos",
    favoriteTherapists: "/app/favoritos/terapeutas",
    favoriteTherapies: "/app/favoritos/terapias",
    payments: "/app/pagamentos",
    invoices: "/app/pagamentos/faturas",
    paymentMethods: "/app/pagamentos/metodos",
    settings: "/app/configuracoes",
    profileSettings: "/app/configuracoes/perfil",
    notificationSettings: "/app/configuracoes/notificacoes",
    privacySettings: "/app/configuracoes/privacidade",
    securitySettings: "/app/configuracoes/seguranca",
    help: "/app/ajuda",
  },
  therapist: {
    home: "/terapeuta",
    agenda: "/terapeuta/agenda",
    patients: "/terapeuta/pacientes",
    patientJourney: (patientId: string) => `/terapeuta/pacientes/${patientId}`,
    sessions: "/terapeuta/sessoes",
    sessionDetail: (bookingId: string) => `/terapeuta/sessoes/${bookingId}`,
    messages: "/terapeuta/mensagens",
    services: "/terapeuta/servicos",
    ownServices: "/terapeuta/servicos/meus",
    finance: "/terapeuta/financeiro",
    reviews: "/terapeuta/avaliacoes",
    insights: "/terapeuta/insights",
    assessorIa: "/terapeuta/assessor-ia",
    profile: "/terapeuta/perfil",
    plan: "/terapeuta/plano",
    settings: "/terapeuta/configuracoes",
    support: "/terapeuta/suporte",
  },
  admin: {
    home: "/admin",
    professionals: "/admin/profissionais",
    verifications: "/admin/profissionais/verificacoes",
    patients: "/admin/pacientes",
    sessions: "/admin/sessoes",
    payments: "/admin/pagamentos",
    reviews: "/admin/avaliacoes",
    subscriptions: "/admin/assinaturas",
    therapies: "/admin/terapias",
    matching: "/admin/matching",
    integrations: "/admin/integracoes",
    security: "/admin/seguranca",
    reports: "/admin/relatorios",
    settings: "/admin/configuracoes",
    support: "/admin/suporte",
  },
} as const;

export const routeAliases = {
  "/como funciona": routes.public.howItWorks,
} as const;
