export const routes = {
  public: {
    home: '/',
    howItWorks: '/como-funciona',
    journey: '/sua-jornada',
    journeyResult: '/sua-jornada/resultado',
    therapists: '/terapeutas',
    therapistProfile: (slug: string) => `/terapeutas/${slug}`,
    reservation: '/reserva',
    reservationSuccess: '/reserva/sucesso',
    therapies: '/terapias',
    therapyDetail: (slug: string) => `/terapias/${slug}`,
    forTherapists: '/para-terapeutas',
    therapistPlans: '/para-terapeutas/planos',
    clientSignIn: '/cliente/login',
    clientSignUp: '/cliente/cadastro',
    therapistSignIn: '/terapeuta/login',
    therapistSignUp: '/terapeuta/cadastro',
    signIn: '/entrar',
    signUp: '/cadastro',
    resetPassword: '/reset-senha',
    help: '/ajuda',
    terms: '/termos',
    privacy: '/privacidade',
  },
  patient: {
    home: '/app',
    sessions: '/app/sessoes',
    upcomingSessions: '/app/sessoes/proximas',
    sessionHistory: '/app/sessoes/historico',
    sessionDetail: (slug: string) => `/app/sessoes/${slug}`,
    messages: '/app/mensagens',
    favorites: '/app/favoritos',
    favoriteTherapists: '/app/favoritos/terapeutas',
    favoriteTherapies: '/app/favoritos/terapias',
    payments: '/app/pagamentos',
    invoices: '/app/pagamentos/faturas',
    paymentMethods: '/app/pagamentos/metodos',
    settings: '/app/configuracoes',
    profileSettings: '/app/configuracoes/perfil',
    notificationSettings: '/app/configuracoes/notificacoes',
    privacySettings: '/app/configuracoes/privacidade',
    securitySettings: '/app/configuracoes/seguranca',
    help: '/app/ajuda',
  },
  therapist: {
    basicHome: '/basico',
    basicAgenda: '/basico/agenda',
    basicPatients: '/basico/pacientes',
    basicSessions: '/basico/sessoes',
    basicMessages: '/basico/mensagens',
    basicServices: '/basico/servicos',
    basicOwnServices: '/basico/servicos/meus',
    basicPayment: '/basico/pagamento',
    basicProfile: '/basico/perfil',
    basicUpgrade: '/basico/upgrade',
    basicSettings: '/basico/configuracoes',
    basicSupport: '/basico/suporte',
    proHome: '/pro',
    proAgenda: '/pro/agenda',
    proPatients: '/pro/pacientes',
    proSessions: '/pro/sessoes',
    proMessages: '/pro/mensagens',
    proServices: '/pro/servicos',
    proFinance: '/pro/financeiro',
    proMetrics: '/pro/metricas',
    proReviews: '/pro/avaliacoes',
    proPlan: '/pro/plano',
    proProfile: '/pro/perfil',
    proSettings: '/pro/configuracoes',
    proSupport: '/pro/suporte',
    plusHome: '/plus',
    plusAgenda: '/plus/agenda',
    plusPatients: '/plus/pacientes',
    plusPatientJourney: (slug: string) => `/plus/pacientes/${slug}`,
    plusSessions: '/plus/sessoes',
    plusMessages: '/plus/mensagens',
    plusServices: '/plus/servicos',
    plusOwnServices: '/plus/servicos/meus',
    plusFinance: '/plus/financeiro',
    plusReviews: '/plus/avaliacoes',
    plusInsights: '/plus/insights',
    plusAssessorIa: '/plus/assessor-ia',
    plusProfile: '/plus/perfil',
    plusSettings: '/plus/configuracoes',
    plusSupport: '/plus/suporte',
  },
  admin: {
    home: '/admin',
    professionals: '/admin/profissionais',
    verifications: '/admin/profissionais/verificacoes',
    patients: '/admin/pacientes',
    sessions: '/admin/sessoes',
    payments: '/admin/pagamentos',
    reviews: '/admin/avaliacoes',
    subscriptions: '/admin/assinaturas',
    therapies: '/admin/terapias',
    matching: '/admin/matching',
    integrations: '/admin/integracoes',
    security: '/admin/seguranca',
    reports: '/admin/relatorios',
    settings: '/admin/configuracoes',
    support: '/admin/suporte',
  },
} as const;

export const routeAliases = {
  '/como funciona': routes.public.howItWorks,
  '/plus/serviços': routes.therapist.plusServices,
  '/plus/avaliações': routes.therapist.plusReviews,
  '/plus/ia': routes.therapist.plusAssessorIa,
} as const;
