-- Compatibility note:
-- This project uses [db.seed].sql_paths in supabase/config.toml because the
-- current Supabase CLI loads seed files as SQL batches and does not process
-- psql meta-commands such as \ir.
--
-- Local reset loads, in order:
--   1. ./seeds/catalog.sql
--   2. ./seeds/local-test-data.sql
--
-- For homologation/producao-like environments, execute only:
--   supabase/seeds/catalog.sql
