import { routes } from "@/lib/routes";

import type { TherapistSearchCard } from "./types";

export const THERAPIST_SEARCH_PAGE_SIZE = 6;

export const therapistSearchHero = {
  titleStart: "Encontre alguém para",
  titleAccent: "caminhar com você.",
  body: "Cada jornada é única. Conheça terapeutas preparados para acolher o momento que você está vivendo e encontre um caminho que faça sentido para você.",
};

export const priceOptions = [
  { label: "Até R$ 100", value: "up-to-100" },
  { label: "R$ 100 a R$ 150", value: "100-150" },
  { label: "Acima de R$ 150", value: "150-plus" },
];

export const availabilityOptions = [
  { label: "Hoje", value: "today" },
  { label: "Amanhã", value: "tomorrow" },
  { label: "Esta semana", value: "week" },
];

export const ratingOptions = [
  { label: "4+ estrelas", value: "4-plus" },
  { label: "4,5+ estrelas", value: "4-5-plus" },
];

export const sortOptions = [
  { label: "Relevância", value: "relevance" },
  { label: "Melhor avaliação", value: "rating" },
  { label: "Menor preço", value: "price_asc" },
  { label: "Próximo horário", value: "next_slot" },
];

export const fallbackTherapists: TherapistSearchCard[] = [
  {
    availabilityBucket: "today",
    cityState: "São Paulo, SP",
    description:
      "Um espaço de acolhimento para quem busca mais clareza, equilíbrio e leveza emocional.",
    durationLabel: "50 min",
    hasVideo: true,
    highlight: "Destaque TES",
    highlightTone: "featured",
    href: routes.public.therapistProfile("ana-oliveira"),
    image: "/therapists/ana-oliveira.png",
    name: "Ana Oliveira",
    nextSlotAt: new Date().toISOString(),
    nextSlotLabel: "Hoje, 18:00",
    priceCents: 12000,
    priceLabel: "R$ 120 / sessão",
    quote: "Me senti acolhida desde a primeira sessão.",
    rating: 4.9,
    ratingLabel: "4,9",
    reviewsLabel: "98 avaliações",
    reviewCount: 98,
    serviceId: "d1000000-0000-4000-8000-000000000001",
    serviceTitle: "Reiki online",
    slug: "ana-oliveira",
    tags: ["Ansiedade", "Autoestima", "Autoconhecimento"],
    themeSlugs: ["equilibrio-emocional", "autoconhecimento"],
    therapyId: "22222222-2222-4222-8222-222222222225",
    therapyName: "Reiki",
    therapySlug: "reiki",
  },
  {
    availabilityBucket: "tomorrow",
    cityState: "Rio de Janeiro, RJ",
    description:
      "Apoio para quem está vivendo mudanças importantes e deseja encontrar novos caminhos.",
    durationLabel: "50 min",
    hasVideo: true,
    highlight: "Destaque TES",
    highlightTone: "featured",
    href: routes.public.therapistProfile("rafael-santos"),
    image: "/therapists/rafael-santos-avatar.png",
    name: "Rafael Santos",
    nextSlotAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    nextSlotLabel: "Amanhã, 09:30",
    priceCents: 12000,
    priceLabel: "R$ 120 / sessão",
    quote: "Ajudou a organizar um momento muito difícil.",
    rating: 4.8,
    ratingLabel: "4,8",
    reviewsLabel: "74 avaliações",
    reviewCount: 74,
    serviceId: "d1000000-0000-4000-8000-000000000002",
    serviceTitle: "Leitura simbólica de Tarô",
    slug: "rafael-santos",
    tags: ["Mudanças de vida", "Propósito", "Equilíbrio emocional"],
    themeSlugs: ["mudancas-de-vida", "equilibrio-emocional"],
    therapyId: "22222222-2222-4222-8222-222222222228",
    therapyName: "Tarô",
    therapySlug: "taro",
  },
  {
    availabilityBucket: "week",
    cityState: "Curitiba, PR",
    description:
      "Escuta cuidadosa para relações, luto e processos de transformação.",
    durationLabel: "50 min",
    hasVideo: false,
    highlight: "Perfil Verificado",
    highlightTone: "verified",
    href: routes.public.therapistProfile("celia-martins"),
    image: "/therapists/celia-martins.png",
    name: "Célia Martins",
    nextSlotAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    nextSlotLabel: "Sex, 14:00",
    priceCents: 14000,
    priceLabel: "R$ 140 / sessão",
    quote: "Senti segurança para falar do que eu sentia.",
    rating: 4.9,
    ratingLabel: "4,9",
    reviewsLabel: "112 avaliações",
    reviewCount: 112,
    serviceId: "d1000000-0000-4000-8000-000000000003",
    serviceTitle: "Constelação Familiar online",
    slug: "celia-martins",
    tags: ["Relacionamentos", "Família", "Padrões"],
    themeSlugs: ["relacionamentos", "autoconhecimento-transformacao"],
    therapyId: "22222222-2222-4222-8222-222222222230",
    therapyName: "Constelação Familiar",
    therapySlug: "constelacao-familiar",
  },
  {
    availabilityBucket: "week",
    cityState: "Belo Horizonte, MG",
    description:
      "Apoio para famílias construírem diálogos mais leves e seguros.",
    durationLabel: "50 min",
    hasVideo: false,
    highlight: "Perfil Verificado",
    highlightTone: "verified",
    href: routes.public.therapistProfile("juliana-costa"),
    image: "/therapists/juliana-costa.png",
    name: "Juliana Costa",
    nextSlotAt: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    nextSlotLabel: "Seg, 10:00",
    priceCents: 9000,
    priceLabel: "R$ 90 / sessão",
    quote: "Nossas conversas em família ficaram mais leves.",
    rating: 4.6,
    ratingLabel: "4,6",
    reviewsLabel: "88 avaliações",
    reviewCount: 88,
    serviceId: "d1000000-0000-4000-8000-000000000004",
    serviceTitle: "Constelação de vínculos",
    slug: "juliana-costa",
    tags: ["Família", "Relacionamentos", "Comunicação"],
    themeSlugs: ["autoconhecimento", "mudancas-de-vida"],
    therapyId: "22222222-2222-4222-8222-222222222230",
    therapyName: "Constelação Familiar",
    therapySlug: "constelacao-familiar",
  },
  {
    availabilityBucket: "week",
    cityState: "Florianópolis, SC",
    description:
      "Cuidado para autoconhecimento, escolhas e transições de vida.",
    durationLabel: "60 min",
    hasVideo: true,
    highlight: "Destaque TES",
    highlightTone: "featured",
    href: routes.public.therapistProfile("lucas-pereira"),
    image: "/therapists/lucas-pereira-avatar.png",
    name: "Lucas Pereira",
    nextSlotAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    nextSlotLabel: "Ter, 16:30",
    priceCents: 17000,
    priceLabel: "R$ 170 / sessão",
    quote: "Me ajudou a entender meu propósito com mais calma.",
    rating: 4.7,
    ratingLabel: "4,7",
    reviewsLabel: "101 avaliações",
    reviewCount: 101,
    serviceId: "d1000000-0000-4000-8000-000000000005",
    serviceTitle: "Tarô e autoconhecimento",
    slug: "lucas-pereira",
    tags: ["Autoconhecimento", "Propósito", "Mudanças de vida"],
    themeSlugs: ["autoconhecimento", "mudancas-de-vida"],
    therapyId: "22222222-2222-4222-8222-222222222228",
    therapyName: "Tarô",
    therapySlug: "taro",
  },
];
